apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: coral-script
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coral-script
    spec:
      containers:
      - name: coral-script
        image: docker.tjvr.org/coral-script
        env:
          - name: PORT
            value: "8000"
        ports:
          - containerPort: 8000
      imagePullSecrets:
      - name: regsecret
---

apiVersion: v1
kind: Service
metadata:
  name: coral-script
spec:
  ports:
  - protocol: TCP
    port: 8000
  selector:
    app: coral-script

